services:
  postgres:
    image: postgres:16-alpine
    container_name: jobtrack-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobtrack
      POSTGRES_PASSWORD: jobtrack123
      POSTGRES_DB: jobtrack_pro
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
